# Site settings
# These are used to personalize your site. You access them via {{ site.title }}, 
# {{ site.email }} and so on. You can create any custom variable you like. They
# will be accessible in the templates via {{ site.myvariable }}.

title: Kankoda
description: >-
  Kankoda builds apps and products for iOS, iPadOS, tvOS, macOS and watchOS, using technologies like Swift, SwiftUI and Swift Package Manager. 

url: https://kankoda.com
email: info@kankoda.com

copyright_year: 2021-2025
copyright_owner: Kankoda Sweden AB
copyright_url: https://kankoda.com

bluesky_username: "@kankoda.bsky.social"
github_username: Kankoda
mastodon_username: kankoda@mastodon.social
twitter_username: kankodahq

assets: /assets/
header_image: /assets/logo/logo.png

urls:
  blog:       /blog
  email:      mailto:info@kankoda.com
  rss:        https://kankoda.com/feed.xml

  appstore:   https://apps.apple.com/us/developer/kankoda-sweden-ab/id516398918
  bluesky:    https://bsky.app/profile/kankoda.bsky.social
  github:     https://github.com/kankoda
  gumroad:    https://kankoda.gumroad.com
  mastodon:   https://mastodon.social/@kankoda
  newsletter: https://kankoda.gumroad.com/subscribe
  twitter:    https://twitter.com/kankodahq

  keyboardkit: https://keyboardkit.com
  keyboardkitpro: https://keyboardkit.com/pro
  licensekit: https://kankoda.com/sdks/licensekit
  licensekit_github: https://github.com/kankoda/licensekit
  wally:      https://wally.app

  docc:       https://www.swift.org/documentation/docc/#:~:text=DocC%20syntax%20—%20called%20documentation%20markup,%2C%20code%20listings%2C%20and%20asides.
  jetpack:    https://developer.android.com/jetpack/compose
  kotlin:     https://kotlinlang.org
  spm:        https://www.swift.org/package-manager/
  swift:      https://developer.apple.com/swift/
  swiftui:    https://developer.apple.com/xcode/swiftui/

  stockholm:  https://www.google.com/maps/place/Stockholm,+Sweden/@59.3262131,17.8172499,11z/data=!3m1!4b1!4m6!3m5!1s0x465f763119640bcb:0xa80d27d3679d7766!8m2!3d59.3293235!4d18.0685808!16zL20vMDZteHM

header:
  pages:
    - pages/home.md
    - pages/apps.md
    - pages/sdks.md
    - pages/blog.md

footer:
  sitemap:
    - index.html
    - pages/about.md
    - pages/sdks.md
    - pages/apps.md

collections_dir: collections

collections:
  apps:
    output: true
    permalink: /apps/:name
  emojikit-features:
    output: true
    permalink: /emojikit/features/:name
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title

  licensekit-features:
    output: true
    permalink: /sdks/licensekit/features/:name/
  vietnameseinput-features:
    output: true
    permalink: /sdks/vietnameseinput/features/:name/

baseurl: ""
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  
include: [".well-known"]

plugins:
  - jekyll-feed
  - jekyll-redirect-from

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "page"
      image: /assets/headers/kankoda.jpg
      page-class: glass-background bg1
  -
    scope:
      type: apps
    values:
      layout: app
      hero-class: devices
      hero-icon-class: app-icon
      page-class: glass-background bg1
  -
    scope:
      type: posts
    values:
      author: danielsaidi
      layout: post
      image: /assets/headers/kankoda.jpg
      page-class: glass-background bg1
  -
    scope:
      type: licensekit-features
    values:
      layout: licensekit-feature
      image: /assets/sdks/licensekit-header.jpg
      page-class: glass-background bg2
  -
    scope:
      type: vietnameseinput-features
    values:
      layout: vietnameseinput-feature
      image: /assets/sdks/vietnameseinput-header.jpg
      page-class: glass-background bg2

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/